default_platform(:ios)

platform :ios do
  desc "Register app"

  lane :register_app do
    produce(
        username: "cinnamondevelopers@gmail.com",
        app_identifier: "fastlane.test.app",
        app_name: "FastlaneTestApp",
        team_name: "Cinnamon doo"
      )
  end

  lane :get_dev_certs do 
    cert(
        development: true
      )

    sigh(
        development: true
        )
  end

  lane :snapshots do 
    run_tests(
      scheme: "FastlaneTestProject_Snapshots"
      )
  end

    lane :tests do 
    run_tests(
      scheme: "FastlaneTestProject",
      devices: ["iPhone 13"]
      )
  end

  lane :beta do
    # sync_code_signing(type: "appstore")
    build_app(scheme: "FastlaneTestProject")
    upload_to_testflight
  end
end
